# Generated by Django 4.2.4 on 2023-08-07 09:47

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('decription', models.TextField(blank=True, max_length=500, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('courier_status', models.CharField(blank=True, choices=[('Available', 'Available'), ('Unavailable', 'Unavailable')], max_length=150, null=True)),
                ('client_id', models.IntegerField(blank=True, null=True)),
                ('client_name', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
